use etlc;
select * from health;

#1. Retrieve the names of all patients in the database. 
select name from health;

#2. List the unique medical conditions present in the dataset.
select distinct(medical_condition) from health;
 
#3. Find the total number of doctors in the healthcare system.
select count(distinct(doctor)) from health;

#4. Retrieve the details of all female patients. 
select * from health where gender='female';

#5. what is the average age of patients in the database.
select avg(age) from health;

#6. Identify the patients who have more than one medical condition.
select name, count(name) from health group by name having count(name)>1;

#7. List the names of all doctors.
select doctor from health;

#8.Identify the most common medical condition among patients. 
select medical_condition, count(medical_condition) from health 
group by medical_condition order by count(medical_condition) desc limit 1,1;

#9.Find the patients who are older than 60 years and have diabetes.
select name, age, medical_condition from health 
where age>60 and medical_condition='diabetes' order by age;

#10.Calculate the total revenue generated by the healthcare system.
select sum(billing_amount) from health;
-- Rs.74,67,285.00/-
 
#11.Find the doctor with the oldest patient.
select name, age, doctor from health order by age desc limit 1,1;

#12.Calculate the average duration of medical visits.
select avg(duration) from health;
select duration from health;
select duration, replace(duration,' days','') from health;
update health set duration=replace(duration,'-','');
select duration from health;
select avg(duration) from health;

#13.Give the names of patients whose name starts with A.
select name from health where name like 'a%';

#14.How many male and female patients are there in dataset.
select gender, count(gender) from health group by gender;

#15.how many patients are normal. 
select count(Test_Results),Test_Results from health 
group by Test_Results having Test_Results='normal';

#16.how many patients are abnormal or Inconclusive.
select count(Test_Results),Test_Results from health 
group by Test_Results having Test_Results!='normal';

#17.how many patients of blood group AB+ are there of age above 52.
select count(*) ,name from health where Blood_Type='AB+' and age>52;

#18. how many patients have paid the bill above 24890.
select count(*) from health where billing_amount>24890;

#19. what are the names of patients having Asthma.
select name, medical_condition from health where medical_condition='asthma';

#20. how many patients have cancer.
select count(*) from health where medical_Condition='cancer';

#21. what are the names and blood groups of patients admitted to room no. 292.
select name, blood_type, room_number from health where room_number='292';

#22. how many males have Arthritis.
select count(*) from health where medical_Condition='Arthritis' and gender='male';

#23. How many patients were admitted to Harris and Sons hospital.
select count(*) as hospital_harris_and_sons from health where hospital='Harris and Sons';

#24. what are the names of patients whose Insurance Provider are Cigna.
select name, Insurance_Provider from health where Insurance_Provider='Cigna';
 
#25. Name the Medical Condition having patients whose ages is greater than average age
select name, medical_condition, age from health where age>(select avg(age) from health);
